
    struct AttribValue
    {
        string key;
        string type;
        string value;
        long length;
    };



    struct EdgeAttribs { 
		string label;
		long from;
        long to; //key
		//map<string, AttribValue>    attrs;
        sequence<AttribValue> attrs;
	};


    struct Node { 
        string type;
        long id;
		//map<string, AttribValue>   attrs;
		sequence<AttribValue> attrs;
        //map<unsigned long, EdgeAttribs> fano;
        sequence<EdgeAttribs> fano;
    };

    //struct DSRGraphTopic
    //{
    //    map<unsigned long, AttribValue> DSRGraph;
    //};


    // Topic for full graph requests
    struct GraphRequest
    {
        string from;
    };

    // --- Test: OrMap with AworSet

    struct PairInt {
        long first;
        long second;
    };
    

    struct DotContext {
        //map<long, long> cc;
        sequence<PairInt> cc;
        sequence<PairInt> dc;
    };


    struct dsValue {
        PairInt pi;
        Node n;
    };

    struct DotKernel {
        //map<PairInt, Node> ds;
        sequence<dsValue> ds;
        DotContext cbase;
    };

    struct AworSet {
        long id;
        DotKernel dk; // Dot kernel
    };

    struct OrMap {
        long id;
        sequence<AworSet> m;
        DotContext cbase;
    };



