
    struct AttribValue
    {
        string key;
        string type;
        string value;
        long length;
    };



    struct EdgeAttribs {
		string label;
		long from;
        long to; //key
		map<string, AttribValue>    attrs;
	};


    struct Node {
        string type;
        string name;
        long id;
        long agent_id;
		map<string, AttribValue>   attrs;
		map<long, EdgeAttribs> fano;
    };

    struct GraphRequest
    {
        string from;
    };


    struct PairInt {
        long first;
        long second;
    };


    struct DotContext {
        map<long, long> cc;
        sequence<PairInt> dc;
    };

    struct DotKernel {
        map<PairInt, Node> ds;
        DotContext cbase;
    };

    struct AworSet {
        long id;
        DotKernel dk;
    };

    struct OrMap {
        long id;
        map<long, AworSet> m;
        DotContext cbase;
    };



