/********************************************************************************
** Form generated from reading UI file 'graph_edge_rt_widget_UI.ui'
**
** Created by: Qt User Interface Compiler version 5.15.13
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef GRAPH_EDGE_RT_WIDGET_UI_H
#define GRAPH_EDGE_RT_WIDGET_UI_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_GraphEdgeRTWidget
{
public:
    QWidget *gridLayoutWidget;
    QGridLayout *gridLayout_2;
    QLabel *label_covariance_matrix;
    QLabel *label_reference;
    QLabel *label_robot;
    QTableWidget *tableWidget_Robot;
    QComboBox *comboBox_reference;
    QTabWidget *tabWidget_covariance_matrix;
    QWidget *Pose;
    QTableWidget *tableWidget_covariance_pose_matrix;
    QWidget *Velocity;
    QTableWidget *tableWidget_covariance_velocity_matrix;
    QWidget *Acceleration;
    QTableWidget *tableWidget_covariance_acceleration_matrix;

    void setupUi(QWidget *GraphEdgeRTWidget)
    {
        if (GraphEdgeRTWidget->objectName().isEmpty())
            GraphEdgeRTWidget->setObjectName(QString::fromUtf8("GraphEdgeRTWidget"));
        GraphEdgeRTWidget->resize(833, 335);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(GraphEdgeRTWidget->sizePolicy().hasHeightForWidth());
        GraphEdgeRTWidget->setSizePolicy(sizePolicy);
        gridLayoutWidget = new QWidget(GraphEdgeRTWidget);
        gridLayoutWidget->setObjectName(QString::fromUtf8("gridLayoutWidget"));
        gridLayoutWidget->setGeometry(QRect(10, 10, 811, 311));
        gridLayout_2 = new QGridLayout(gridLayoutWidget);
        gridLayout_2->setObjectName(QString::fromUtf8("gridLayout_2"));
        gridLayout_2->setSizeConstraint(QLayout::SetDefaultConstraint);
        gridLayout_2->setHorizontalSpacing(6);
        gridLayout_2->setContentsMargins(0, 0, 0, 0);
        label_covariance_matrix = new QLabel(gridLayoutWidget);
        label_covariance_matrix->setObjectName(QString::fromUtf8("label_covariance_matrix"));
        QSizePolicy sizePolicy1(QSizePolicy::Minimum, QSizePolicy::Minimum);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(label_covariance_matrix->sizePolicy().hasHeightForWidth());
        label_covariance_matrix->setSizePolicy(sizePolicy1);
        label_covariance_matrix->setAlignment(Qt::AlignCenter);
        label_covariance_matrix->setWordWrap(false);

        gridLayout_2->addWidget(label_covariance_matrix, 1, 1, 1, 1);

        label_reference = new QLabel(gridLayoutWidget);
        label_reference->setObjectName(QString::fromUtf8("label_reference"));
        label_reference->setAlignment(Qt::AlignCenter);
        label_reference->setWordWrap(false);

        gridLayout_2->addWidget(label_reference, 0, 0, 1, 1);

        label_robot = new QLabel(gridLayoutWidget);
        label_robot->setObjectName(QString::fromUtf8("label_robot"));
        sizePolicy1.setHeightForWidth(label_robot->sizePolicy().hasHeightForWidth());
        label_robot->setSizePolicy(sizePolicy1);
        label_robot->setMaximumSize(QSize(500, 25));
        label_robot->setAlignment(Qt::AlignCenter);
        label_robot->setWordWrap(false);

        gridLayout_2->addWidget(label_robot, 1, 0, 1, 1);

        tableWidget_Robot = new QTableWidget(gridLayoutWidget);
        if (tableWidget_Robot->columnCount() < 4)
            tableWidget_Robot->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWidget_Robot->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWidget_Robot->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWidget_Robot->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWidget_Robot->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        if (tableWidget_Robot->rowCount() < 8)
            tableWidget_Robot->setRowCount(8);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWidget_Robot->setVerticalHeaderItem(0, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWidget_Robot->setVerticalHeaderItem(1, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWidget_Robot->setVerticalHeaderItem(2, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWidget_Robot->setVerticalHeaderItem(3, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWidget_Robot->setVerticalHeaderItem(4, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWidget_Robot->setVerticalHeaderItem(5, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWidget_Robot->setVerticalHeaderItem(6, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWidget_Robot->setVerticalHeaderItem(7, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWidget_Robot->setItem(0, 0, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWidget_Robot->setItem(0, 1, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWidget_Robot->setItem(0, 2, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWidget_Robot->setItem(0, 3, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWidget_Robot->setItem(1, 0, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWidget_Robot->setItem(1, 1, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWidget_Robot->setItem(1, 2, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWidget_Robot->setItem(1, 3, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWidget_Robot->setItem(2, 0, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWidget_Robot->setItem(2, 1, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWidget_Robot->setItem(2, 2, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWidget_Robot->setItem(2, 3, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWidget_Robot->setItem(3, 0, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWidget_Robot->setItem(3, 1, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWidget_Robot->setItem(3, 2, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWidget_Robot->setItem(3, 3, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWidget_Robot->setItem(4, 0, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWidget_Robot->setItem(4, 1, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWidget_Robot->setItem(4, 2, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWidget_Robot->setItem(4, 3, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableWidget_Robot->setItem(5, 0, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tableWidget_Robot->setItem(5, 1, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tableWidget_Robot->setItem(5, 2, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        tableWidget_Robot->setItem(5, 3, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        tableWidget_Robot->setItem(6, 0, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        tableWidget_Robot->setItem(6, 1, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tableWidget_Robot->setItem(6, 2, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        tableWidget_Robot->setItem(7, 0, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tableWidget_Robot->setItem(7, 1, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        tableWidget_Robot->setItem(7, 2, __qtablewidgetitem41);
        tableWidget_Robot->setObjectName(QString::fromUtf8("tableWidget_Robot"));
        sizePolicy1.setHeightForWidth(tableWidget_Robot->sizePolicy().hasHeightForWidth());
        tableWidget_Robot->setSizePolicy(sizePolicy1);
        tableWidget_Robot->setMaximumSize(QSize(16777215, 16777215));
        tableWidget_Robot->setLayoutDirection(Qt::LeftToRight);
        tableWidget_Robot->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableWidget_Robot->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableWidget_Robot->setAutoScroll(false);
        tableWidget_Robot->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tableWidget_Robot->setTabKeyNavigation(false);
        tableWidget_Robot->setProperty("showDropIndicator", QVariant(false));
        tableWidget_Robot->setTextElideMode(Qt::ElideMiddle);
        tableWidget_Robot->setVerticalScrollMode(QAbstractItemView::ScrollPerPixel);
        tableWidget_Robot->setShowGrid(true);
        tableWidget_Robot->setGridStyle(Qt::SolidLine);
        tableWidget_Robot->setSortingEnabled(false);
        tableWidget_Robot->setWordWrap(false);
        tableWidget_Robot->setCornerButtonEnabled(false);
        tableWidget_Robot->horizontalHeader()->setVisible(true);
        tableWidget_Robot->horizontalHeader()->setMinimumSectionSize(20);
        tableWidget_Robot->horizontalHeader()->setDefaultSectionSize(75);
        tableWidget_Robot->horizontalHeader()->setHighlightSections(false);
        tableWidget_Robot->verticalHeader()->setVisible(true);
        tableWidget_Robot->verticalHeader()->setCascadingSectionResizes(false);
        tableWidget_Robot->verticalHeader()->setMinimumSectionSize(20);
        tableWidget_Robot->verticalHeader()->setDefaultSectionSize(27);
        tableWidget_Robot->verticalHeader()->setHighlightSections(false);

        gridLayout_2->addWidget(tableWidget_Robot, 3, 0, 1, 1);

        comboBox_reference = new QComboBox(gridLayoutWidget);
        comboBox_reference->addItem(QString());
        comboBox_reference->addItem(QString());
        comboBox_reference->setObjectName(QString::fromUtf8("comboBox_reference"));

        gridLayout_2->addWidget(comboBox_reference, 0, 1, 1, 1);

        tabWidget_covariance_matrix = new QTabWidget(gridLayoutWidget);
        tabWidget_covariance_matrix->setObjectName(QString::fromUtf8("tabWidget_covariance_matrix"));
        sizePolicy1.setHeightForWidth(tabWidget_covariance_matrix->sizePolicy().hasHeightForWidth());
        tabWidget_covariance_matrix->setSizePolicy(sizePolicy1);
        Pose = new QWidget();
        Pose->setObjectName(QString::fromUtf8("Pose"));
        tableWidget_covariance_pose_matrix = new QTableWidget(Pose);
        if (tableWidget_covariance_pose_matrix->columnCount() < 6)
            tableWidget_covariance_pose_matrix->setColumnCount(6);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setHorizontalHeaderItem(0, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setHorizontalHeaderItem(1, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setHorizontalHeaderItem(2, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setHorizontalHeaderItem(3, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setHorizontalHeaderItem(4, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setHorizontalHeaderItem(5, __qtablewidgetitem47);
        if (tableWidget_covariance_pose_matrix->rowCount() < 6)
            tableWidget_covariance_pose_matrix->setRowCount(6);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setVerticalHeaderItem(0, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setVerticalHeaderItem(1, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setVerticalHeaderItem(2, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setVerticalHeaderItem(3, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setVerticalHeaderItem(4, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setVerticalHeaderItem(5, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(0, 0, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(0, 1, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(0, 2, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(0, 3, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(0, 4, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(0, 5, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(1, 0, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(1, 1, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(1, 2, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(1, 3, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(1, 4, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(1, 5, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(2, 0, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(2, 1, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(2, 2, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(2, 3, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(2, 4, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(2, 5, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(3, 0, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(3, 1, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(3, 2, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(3, 3, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(3, 4, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(3, 5, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(4, 0, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(4, 1, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(4, 2, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(4, 3, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(4, 4, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(4, 5, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(5, 0, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(5, 1, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(5, 2, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(5, 3, __qtablewidgetitem87);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(5, 4, __qtablewidgetitem88);
        QTableWidgetItem *__qtablewidgetitem89 = new QTableWidgetItem();
        tableWidget_covariance_pose_matrix->setItem(5, 5, __qtablewidgetitem89);
        tableWidget_covariance_pose_matrix->setObjectName(QString::fromUtf8("tableWidget_covariance_pose_matrix"));
        tableWidget_covariance_pose_matrix->setGeometry(QRect(0, 10, 389, 191));
        QSizePolicy sizePolicy2(QSizePolicy::Preferred, QSizePolicy::Minimum);
        sizePolicy2.setHorizontalStretch(0);
        sizePolicy2.setVerticalStretch(0);
        sizePolicy2.setHeightForWidth(tableWidget_covariance_pose_matrix->sizePolicy().hasHeightForWidth());
        tableWidget_covariance_pose_matrix->setSizePolicy(sizePolicy2);
        tableWidget_covariance_pose_matrix->setLayoutDirection(Qt::LeftToRight);
        tableWidget_covariance_pose_matrix->setAutoFillBackground(false);
        tableWidget_covariance_pose_matrix->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableWidget_covariance_pose_matrix->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableWidget_covariance_pose_matrix->setAutoScroll(false);
        tableWidget_covariance_pose_matrix->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tableWidget_covariance_pose_matrix->setTabKeyNavigation(false);
        tableWidget_covariance_pose_matrix->setProperty("showDropIndicator", QVariant(false));
        tableWidget_covariance_pose_matrix->setTextElideMode(Qt::ElideMiddle);
        tableWidget_covariance_pose_matrix->setVerticalScrollMode(QAbstractItemView::ScrollPerPixel);
        tableWidget_covariance_pose_matrix->setShowGrid(true);
        tableWidget_covariance_pose_matrix->setGridStyle(Qt::SolidLine);
        tableWidget_covariance_pose_matrix->setSortingEnabled(false);
        tableWidget_covariance_pose_matrix->setWordWrap(false);
        tableWidget_covariance_pose_matrix->setCornerButtonEnabled(false);
        tableWidget_covariance_pose_matrix->horizontalHeader()->setVisible(false);
        tableWidget_covariance_pose_matrix->horizontalHeader()->setMinimumSectionSize(20);
        tableWidget_covariance_pose_matrix->horizontalHeader()->setDefaultSectionSize(65);
        tableWidget_covariance_pose_matrix->horizontalHeader()->setHighlightSections(false);
        tableWidget_covariance_pose_matrix->verticalHeader()->setVisible(false);
        tableWidget_covariance_pose_matrix->verticalHeader()->setCascadingSectionResizes(false);
        tableWidget_covariance_pose_matrix->verticalHeader()->setMinimumSectionSize(20);
        tableWidget_covariance_pose_matrix->verticalHeader()->setDefaultSectionSize(31);
        tableWidget_covariance_pose_matrix->verticalHeader()->setHighlightSections(false);
        tabWidget_covariance_matrix->addTab(Pose, QString());
        Velocity = new QWidget();
        Velocity->setObjectName(QString::fromUtf8("Velocity"));
        tableWidget_covariance_velocity_matrix = new QTableWidget(Velocity);
        if (tableWidget_covariance_velocity_matrix->columnCount() < 6)
            tableWidget_covariance_velocity_matrix->setColumnCount(6);
        QTableWidgetItem *__qtablewidgetitem90 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setHorizontalHeaderItem(0, __qtablewidgetitem90);
        QTableWidgetItem *__qtablewidgetitem91 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setHorizontalHeaderItem(1, __qtablewidgetitem91);
        QTableWidgetItem *__qtablewidgetitem92 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setHorizontalHeaderItem(2, __qtablewidgetitem92);
        QTableWidgetItem *__qtablewidgetitem93 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setHorizontalHeaderItem(3, __qtablewidgetitem93);
        QTableWidgetItem *__qtablewidgetitem94 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setHorizontalHeaderItem(4, __qtablewidgetitem94);
        QTableWidgetItem *__qtablewidgetitem95 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setHorizontalHeaderItem(5, __qtablewidgetitem95);
        if (tableWidget_covariance_velocity_matrix->rowCount() < 6)
            tableWidget_covariance_velocity_matrix->setRowCount(6);
        QTableWidgetItem *__qtablewidgetitem96 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setVerticalHeaderItem(0, __qtablewidgetitem96);
        QTableWidgetItem *__qtablewidgetitem97 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setVerticalHeaderItem(1, __qtablewidgetitem97);
        QTableWidgetItem *__qtablewidgetitem98 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setVerticalHeaderItem(2, __qtablewidgetitem98);
        QTableWidgetItem *__qtablewidgetitem99 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setVerticalHeaderItem(3, __qtablewidgetitem99);
        QTableWidgetItem *__qtablewidgetitem100 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setVerticalHeaderItem(4, __qtablewidgetitem100);
        QTableWidgetItem *__qtablewidgetitem101 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setVerticalHeaderItem(5, __qtablewidgetitem101);
        QTableWidgetItem *__qtablewidgetitem102 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(0, 0, __qtablewidgetitem102);
        QTableWidgetItem *__qtablewidgetitem103 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(0, 1, __qtablewidgetitem103);
        QTableWidgetItem *__qtablewidgetitem104 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(0, 2, __qtablewidgetitem104);
        QTableWidgetItem *__qtablewidgetitem105 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(0, 3, __qtablewidgetitem105);
        QTableWidgetItem *__qtablewidgetitem106 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(0, 4, __qtablewidgetitem106);
        QTableWidgetItem *__qtablewidgetitem107 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(0, 5, __qtablewidgetitem107);
        QTableWidgetItem *__qtablewidgetitem108 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(1, 0, __qtablewidgetitem108);
        QTableWidgetItem *__qtablewidgetitem109 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(1, 1, __qtablewidgetitem109);
        QTableWidgetItem *__qtablewidgetitem110 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(1, 2, __qtablewidgetitem110);
        QTableWidgetItem *__qtablewidgetitem111 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(1, 3, __qtablewidgetitem111);
        QTableWidgetItem *__qtablewidgetitem112 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(1, 4, __qtablewidgetitem112);
        QTableWidgetItem *__qtablewidgetitem113 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(1, 5, __qtablewidgetitem113);
        QTableWidgetItem *__qtablewidgetitem114 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(2, 0, __qtablewidgetitem114);
        QTableWidgetItem *__qtablewidgetitem115 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(2, 1, __qtablewidgetitem115);
        QTableWidgetItem *__qtablewidgetitem116 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(2, 2, __qtablewidgetitem116);
        QTableWidgetItem *__qtablewidgetitem117 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(2, 3, __qtablewidgetitem117);
        QTableWidgetItem *__qtablewidgetitem118 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(2, 4, __qtablewidgetitem118);
        QTableWidgetItem *__qtablewidgetitem119 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(2, 5, __qtablewidgetitem119);
        QTableWidgetItem *__qtablewidgetitem120 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(3, 0, __qtablewidgetitem120);
        QTableWidgetItem *__qtablewidgetitem121 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(3, 1, __qtablewidgetitem121);
        QTableWidgetItem *__qtablewidgetitem122 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(3, 2, __qtablewidgetitem122);
        QTableWidgetItem *__qtablewidgetitem123 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(3, 3, __qtablewidgetitem123);
        QTableWidgetItem *__qtablewidgetitem124 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(3, 4, __qtablewidgetitem124);
        QTableWidgetItem *__qtablewidgetitem125 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(3, 5, __qtablewidgetitem125);
        QTableWidgetItem *__qtablewidgetitem126 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(4, 0, __qtablewidgetitem126);
        QTableWidgetItem *__qtablewidgetitem127 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(4, 1, __qtablewidgetitem127);
        QTableWidgetItem *__qtablewidgetitem128 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(4, 2, __qtablewidgetitem128);
        QTableWidgetItem *__qtablewidgetitem129 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(4, 3, __qtablewidgetitem129);
        QTableWidgetItem *__qtablewidgetitem130 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(4, 4, __qtablewidgetitem130);
        QTableWidgetItem *__qtablewidgetitem131 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(4, 5, __qtablewidgetitem131);
        QTableWidgetItem *__qtablewidgetitem132 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(5, 0, __qtablewidgetitem132);
        QTableWidgetItem *__qtablewidgetitem133 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(5, 1, __qtablewidgetitem133);
        QTableWidgetItem *__qtablewidgetitem134 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(5, 2, __qtablewidgetitem134);
        QTableWidgetItem *__qtablewidgetitem135 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(5, 3, __qtablewidgetitem135);
        QTableWidgetItem *__qtablewidgetitem136 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(5, 4, __qtablewidgetitem136);
        QTableWidgetItem *__qtablewidgetitem137 = new QTableWidgetItem();
        tableWidget_covariance_velocity_matrix->setItem(5, 5, __qtablewidgetitem137);
        tableWidget_covariance_velocity_matrix->setObjectName(QString::fromUtf8("tableWidget_covariance_velocity_matrix"));
        tableWidget_covariance_velocity_matrix->setGeometry(QRect(0, 10, 391, 191));
        sizePolicy2.setHeightForWidth(tableWidget_covariance_velocity_matrix->sizePolicy().hasHeightForWidth());
        tableWidget_covariance_velocity_matrix->setSizePolicy(sizePolicy2);
        tableWidget_covariance_velocity_matrix->setLayoutDirection(Qt::LeftToRight);
        tableWidget_covariance_velocity_matrix->setAutoFillBackground(false);
        tableWidget_covariance_velocity_matrix->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableWidget_covariance_velocity_matrix->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableWidget_covariance_velocity_matrix->setAutoScroll(false);
        tableWidget_covariance_velocity_matrix->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tableWidget_covariance_velocity_matrix->setTabKeyNavigation(false);
        tableWidget_covariance_velocity_matrix->setProperty("showDropIndicator", QVariant(false));
        tableWidget_covariance_velocity_matrix->setTextElideMode(Qt::ElideMiddle);
        tableWidget_covariance_velocity_matrix->setVerticalScrollMode(QAbstractItemView::ScrollPerPixel);
        tableWidget_covariance_velocity_matrix->setShowGrid(true);
        tableWidget_covariance_velocity_matrix->setGridStyle(Qt::SolidLine);
        tableWidget_covariance_velocity_matrix->setSortingEnabled(false);
        tableWidget_covariance_velocity_matrix->setWordWrap(false);
        tableWidget_covariance_velocity_matrix->setCornerButtonEnabled(false);
        tableWidget_covariance_velocity_matrix->horizontalHeader()->setVisible(false);
        tableWidget_covariance_velocity_matrix->horizontalHeader()->setMinimumSectionSize(20);
        tableWidget_covariance_velocity_matrix->horizontalHeader()->setDefaultSectionSize(65);
        tableWidget_covariance_velocity_matrix->horizontalHeader()->setHighlightSections(false);
        tableWidget_covariance_velocity_matrix->verticalHeader()->setVisible(false);
        tableWidget_covariance_velocity_matrix->verticalHeader()->setCascadingSectionResizes(false);
        tableWidget_covariance_velocity_matrix->verticalHeader()->setMinimumSectionSize(20);
        tableWidget_covariance_velocity_matrix->verticalHeader()->setDefaultSectionSize(31);
        tableWidget_covariance_velocity_matrix->verticalHeader()->setHighlightSections(false);
        tabWidget_covariance_matrix->addTab(Velocity, QString());
        Acceleration = new QWidget();
        Acceleration->setObjectName(QString::fromUtf8("Acceleration"));
        tableWidget_covariance_acceleration_matrix = new QTableWidget(Acceleration);
        if (tableWidget_covariance_acceleration_matrix->columnCount() < 6)
            tableWidget_covariance_acceleration_matrix->setColumnCount(6);
        QTableWidgetItem *__qtablewidgetitem138 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setHorizontalHeaderItem(0, __qtablewidgetitem138);
        QTableWidgetItem *__qtablewidgetitem139 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setHorizontalHeaderItem(1, __qtablewidgetitem139);
        QTableWidgetItem *__qtablewidgetitem140 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setHorizontalHeaderItem(2, __qtablewidgetitem140);
        QTableWidgetItem *__qtablewidgetitem141 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setHorizontalHeaderItem(3, __qtablewidgetitem141);
        QTableWidgetItem *__qtablewidgetitem142 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setHorizontalHeaderItem(4, __qtablewidgetitem142);
        QTableWidgetItem *__qtablewidgetitem143 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setHorizontalHeaderItem(5, __qtablewidgetitem143);
        if (tableWidget_covariance_acceleration_matrix->rowCount() < 6)
            tableWidget_covariance_acceleration_matrix->setRowCount(6);
        QTableWidgetItem *__qtablewidgetitem144 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setVerticalHeaderItem(0, __qtablewidgetitem144);
        QTableWidgetItem *__qtablewidgetitem145 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setVerticalHeaderItem(1, __qtablewidgetitem145);
        QTableWidgetItem *__qtablewidgetitem146 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setVerticalHeaderItem(2, __qtablewidgetitem146);
        QTableWidgetItem *__qtablewidgetitem147 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setVerticalHeaderItem(3, __qtablewidgetitem147);
        QTableWidgetItem *__qtablewidgetitem148 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setVerticalHeaderItem(4, __qtablewidgetitem148);
        QTableWidgetItem *__qtablewidgetitem149 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setVerticalHeaderItem(5, __qtablewidgetitem149);
        QTableWidgetItem *__qtablewidgetitem150 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(0, 0, __qtablewidgetitem150);
        QTableWidgetItem *__qtablewidgetitem151 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(0, 1, __qtablewidgetitem151);
        QTableWidgetItem *__qtablewidgetitem152 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(0, 2, __qtablewidgetitem152);
        QTableWidgetItem *__qtablewidgetitem153 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(0, 3, __qtablewidgetitem153);
        QTableWidgetItem *__qtablewidgetitem154 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(0, 4, __qtablewidgetitem154);
        QTableWidgetItem *__qtablewidgetitem155 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(0, 5, __qtablewidgetitem155);
        QTableWidgetItem *__qtablewidgetitem156 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(1, 0, __qtablewidgetitem156);
        QTableWidgetItem *__qtablewidgetitem157 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(1, 1, __qtablewidgetitem157);
        QTableWidgetItem *__qtablewidgetitem158 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(1, 2, __qtablewidgetitem158);
        QTableWidgetItem *__qtablewidgetitem159 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(1, 3, __qtablewidgetitem159);
        QTableWidgetItem *__qtablewidgetitem160 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(1, 4, __qtablewidgetitem160);
        QTableWidgetItem *__qtablewidgetitem161 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(1, 5, __qtablewidgetitem161);
        QTableWidgetItem *__qtablewidgetitem162 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(2, 0, __qtablewidgetitem162);
        QTableWidgetItem *__qtablewidgetitem163 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(2, 1, __qtablewidgetitem163);
        QTableWidgetItem *__qtablewidgetitem164 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(2, 2, __qtablewidgetitem164);
        QTableWidgetItem *__qtablewidgetitem165 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(2, 3, __qtablewidgetitem165);
        QTableWidgetItem *__qtablewidgetitem166 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(2, 4, __qtablewidgetitem166);
        QTableWidgetItem *__qtablewidgetitem167 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(2, 5, __qtablewidgetitem167);
        QTableWidgetItem *__qtablewidgetitem168 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(3, 0, __qtablewidgetitem168);
        QTableWidgetItem *__qtablewidgetitem169 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(3, 1, __qtablewidgetitem169);
        QTableWidgetItem *__qtablewidgetitem170 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(3, 2, __qtablewidgetitem170);
        QTableWidgetItem *__qtablewidgetitem171 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(3, 3, __qtablewidgetitem171);
        QTableWidgetItem *__qtablewidgetitem172 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(3, 4, __qtablewidgetitem172);
        QTableWidgetItem *__qtablewidgetitem173 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(3, 5, __qtablewidgetitem173);
        QTableWidgetItem *__qtablewidgetitem174 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(4, 0, __qtablewidgetitem174);
        QTableWidgetItem *__qtablewidgetitem175 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(4, 1, __qtablewidgetitem175);
        QTableWidgetItem *__qtablewidgetitem176 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(4, 2, __qtablewidgetitem176);
        QTableWidgetItem *__qtablewidgetitem177 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(4, 3, __qtablewidgetitem177);
        QTableWidgetItem *__qtablewidgetitem178 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(4, 4, __qtablewidgetitem178);
        QTableWidgetItem *__qtablewidgetitem179 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(4, 5, __qtablewidgetitem179);
        QTableWidgetItem *__qtablewidgetitem180 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(5, 0, __qtablewidgetitem180);
        QTableWidgetItem *__qtablewidgetitem181 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(5, 1, __qtablewidgetitem181);
        QTableWidgetItem *__qtablewidgetitem182 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(5, 2, __qtablewidgetitem182);
        QTableWidgetItem *__qtablewidgetitem183 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(5, 3, __qtablewidgetitem183);
        QTableWidgetItem *__qtablewidgetitem184 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(5, 4, __qtablewidgetitem184);
        QTableWidgetItem *__qtablewidgetitem185 = new QTableWidgetItem();
        tableWidget_covariance_acceleration_matrix->setItem(5, 5, __qtablewidgetitem185);
        tableWidget_covariance_acceleration_matrix->setObjectName(QString::fromUtf8("tableWidget_covariance_acceleration_matrix"));
        tableWidget_covariance_acceleration_matrix->setGeometry(QRect(0, 10, 389, 191));
        sizePolicy2.setHeightForWidth(tableWidget_covariance_acceleration_matrix->sizePolicy().hasHeightForWidth());
        tableWidget_covariance_acceleration_matrix->setSizePolicy(sizePolicy2);
        tableWidget_covariance_acceleration_matrix->setLayoutDirection(Qt::LeftToRight);
        tableWidget_covariance_acceleration_matrix->setAutoFillBackground(false);
        tableWidget_covariance_acceleration_matrix->setVerticalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableWidget_covariance_acceleration_matrix->setHorizontalScrollBarPolicy(Qt::ScrollBarAlwaysOff);
        tableWidget_covariance_acceleration_matrix->setAutoScroll(false);
        tableWidget_covariance_acceleration_matrix->setEditTriggers(QAbstractItemView::NoEditTriggers);
        tableWidget_covariance_acceleration_matrix->setTabKeyNavigation(false);
        tableWidget_covariance_acceleration_matrix->setProperty("showDropIndicator", QVariant(false));
        tableWidget_covariance_acceleration_matrix->setTextElideMode(Qt::ElideMiddle);
        tableWidget_covariance_acceleration_matrix->setVerticalScrollMode(QAbstractItemView::ScrollPerPixel);
        tableWidget_covariance_acceleration_matrix->setShowGrid(true);
        tableWidget_covariance_acceleration_matrix->setGridStyle(Qt::SolidLine);
        tableWidget_covariance_acceleration_matrix->setSortingEnabled(false);
        tableWidget_covariance_acceleration_matrix->setWordWrap(false);
        tableWidget_covariance_acceleration_matrix->setCornerButtonEnabled(false);
        tableWidget_covariance_acceleration_matrix->horizontalHeader()->setVisible(false);
        tableWidget_covariance_acceleration_matrix->horizontalHeader()->setMinimumSectionSize(20);
        tableWidget_covariance_acceleration_matrix->horizontalHeader()->setDefaultSectionSize(65);
        tableWidget_covariance_acceleration_matrix->horizontalHeader()->setHighlightSections(false);
        tableWidget_covariance_acceleration_matrix->verticalHeader()->setVisible(false);
        tableWidget_covariance_acceleration_matrix->verticalHeader()->setCascadingSectionResizes(false);
        tableWidget_covariance_acceleration_matrix->verticalHeader()->setMinimumSectionSize(20);
        tableWidget_covariance_acceleration_matrix->verticalHeader()->setDefaultSectionSize(31);
        tableWidget_covariance_acceleration_matrix->verticalHeader()->setHighlightSections(false);
        tabWidget_covariance_matrix->addTab(Acceleration, QString());

        gridLayout_2->addWidget(tabWidget_covariance_matrix, 3, 1, 1, 1);


        retranslateUi(GraphEdgeRTWidget);

        tabWidget_covariance_matrix->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(GraphEdgeRTWidget);
    } // setupUi

    void retranslateUi(QWidget *GraphEdgeRTWidget)
    {
        GraphEdgeRTWidget->setWindowTitle(QCoreApplication::translate("GraphEdgeRTWidget", "Form", nullptr));
        label_covariance_matrix->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Covariance Matix", nullptr));
        label_reference->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Reference:", nullptr));
        label_robot->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Robot", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWidget_Robot->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("GraphEdgeRTWidget", "X", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWidget_Robot->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Y", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWidget_Robot->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Z", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWidget_Robot->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("GraphEdgeRTWidget", "W", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = tableWidget_Robot->verticalHeaderItem(0);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Position", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWidget_Robot->verticalHeaderItem(1);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Ang (R)", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWidget_Robot->verticalHeaderItem(2);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Ang (\302\272)", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWidget_Robot->verticalHeaderItem(3);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Ang (Q)", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableWidget_Robot->verticalHeaderItem(4);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Linear Vel", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWidget_Robot->verticalHeaderItem(5);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Rot Vel (R/s)", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWidget_Robot->verticalHeaderItem(6);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Linear Acc", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWidget_Robot->verticalHeaderItem(7);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("GraphEdgeRTWidget", "Rot Acc (R/s\302\262)", nullptr));

        const bool __sortingEnabled = tableWidget_Robot->isSortingEnabled();
        tableWidget_Robot->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem12 = tableWidget_Robot->item(0, 0);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableWidget_Robot->item(0, 1);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableWidget_Robot->item(0, 2);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableWidget_Robot->item(1, 0);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = tableWidget_Robot->item(1, 1);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = tableWidget_Robot->item(1, 2);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = tableWidget_Robot->item(2, 0);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = tableWidget_Robot->item(2, 1);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = tableWidget_Robot->item(2, 2);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = tableWidget_Robot->item(3, 0);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = tableWidget_Robot->item(3, 1);
        ___qtablewidgetitem22->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = tableWidget_Robot->item(3, 2);
        ___qtablewidgetitem23->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = tableWidget_Robot->item(3, 3);
        ___qtablewidgetitem24->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = tableWidget_Robot->item(4, 0);
        ___qtablewidgetitem25->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = tableWidget_Robot->item(4, 1);
        ___qtablewidgetitem26->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem27 = tableWidget_Robot->item(4, 2);
        ___qtablewidgetitem27->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem28 = tableWidget_Robot->item(5, 0);
        ___qtablewidgetitem28->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem29 = tableWidget_Robot->item(5, 1);
        ___qtablewidgetitem29->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem30 = tableWidget_Robot->item(5, 2);
        ___qtablewidgetitem30->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem31 = tableWidget_Robot->item(6, 0);
        ___qtablewidgetitem31->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem32 = tableWidget_Robot->item(6, 1);
        ___qtablewidgetitem32->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem33 = tableWidget_Robot->item(6, 2);
        ___qtablewidgetitem33->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem34 = tableWidget_Robot->item(7, 0);
        ___qtablewidgetitem34->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem35 = tableWidget_Robot->item(7, 1);
        ___qtablewidgetitem35->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem36 = tableWidget_Robot->item(7, 2);
        ___qtablewidgetitem36->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        tableWidget_Robot->setSortingEnabled(__sortingEnabled);

        comboBox_reference->setItemText(0, QCoreApplication::translate("GraphEdgeRTWidget", "root", nullptr));
        comboBox_reference->setItemText(1, QCoreApplication::translate("GraphEdgeRTWidget", "parent", nullptr));


        const bool __sortingEnabled1 = tableWidget_covariance_pose_matrix->isSortingEnabled();
        tableWidget_covariance_pose_matrix->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem37 = tableWidget_covariance_pose_matrix->item(0, 0);
        ___qtablewidgetitem37->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem38 = tableWidget_covariance_pose_matrix->item(0, 1);
        ___qtablewidgetitem38->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem39 = tableWidget_covariance_pose_matrix->item(0, 2);
        ___qtablewidgetitem39->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem40 = tableWidget_covariance_pose_matrix->item(0, 3);
        ___qtablewidgetitem40->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem41 = tableWidget_covariance_pose_matrix->item(0, 4);
        ___qtablewidgetitem41->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem42 = tableWidget_covariance_pose_matrix->item(0, 5);
        ___qtablewidgetitem42->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem43 = tableWidget_covariance_pose_matrix->item(1, 0);
        ___qtablewidgetitem43->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem44 = tableWidget_covariance_pose_matrix->item(1, 1);
        ___qtablewidgetitem44->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem45 = tableWidget_covariance_pose_matrix->item(1, 2);
        ___qtablewidgetitem45->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem46 = tableWidget_covariance_pose_matrix->item(1, 3);
        ___qtablewidgetitem46->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem47 = tableWidget_covariance_pose_matrix->item(1, 4);
        ___qtablewidgetitem47->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem48 = tableWidget_covariance_pose_matrix->item(1, 5);
        ___qtablewidgetitem48->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem49 = tableWidget_covariance_pose_matrix->item(2, 0);
        ___qtablewidgetitem49->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem50 = tableWidget_covariance_pose_matrix->item(2, 1);
        ___qtablewidgetitem50->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem51 = tableWidget_covariance_pose_matrix->item(2, 2);
        ___qtablewidgetitem51->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem52 = tableWidget_covariance_pose_matrix->item(2, 3);
        ___qtablewidgetitem52->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem53 = tableWidget_covariance_pose_matrix->item(2, 4);
        ___qtablewidgetitem53->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem54 = tableWidget_covariance_pose_matrix->item(2, 5);
        ___qtablewidgetitem54->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem55 = tableWidget_covariance_pose_matrix->item(3, 0);
        ___qtablewidgetitem55->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem56 = tableWidget_covariance_pose_matrix->item(3, 1);
        ___qtablewidgetitem56->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem57 = tableWidget_covariance_pose_matrix->item(3, 2);
        ___qtablewidgetitem57->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem58 = tableWidget_covariance_pose_matrix->item(3, 3);
        ___qtablewidgetitem58->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem59 = tableWidget_covariance_pose_matrix->item(3, 4);
        ___qtablewidgetitem59->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem60 = tableWidget_covariance_pose_matrix->item(3, 5);
        ___qtablewidgetitem60->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem61 = tableWidget_covariance_pose_matrix->item(4, 0);
        ___qtablewidgetitem61->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem62 = tableWidget_covariance_pose_matrix->item(4, 1);
        ___qtablewidgetitem62->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem63 = tableWidget_covariance_pose_matrix->item(4, 2);
        ___qtablewidgetitem63->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem64 = tableWidget_covariance_pose_matrix->item(4, 3);
        ___qtablewidgetitem64->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem65 = tableWidget_covariance_pose_matrix->item(4, 4);
        ___qtablewidgetitem65->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem66 = tableWidget_covariance_pose_matrix->item(4, 5);
        ___qtablewidgetitem66->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem67 = tableWidget_covariance_pose_matrix->item(5, 0);
        ___qtablewidgetitem67->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem68 = tableWidget_covariance_pose_matrix->item(5, 1);
        ___qtablewidgetitem68->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem69 = tableWidget_covariance_pose_matrix->item(5, 2);
        ___qtablewidgetitem69->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem70 = tableWidget_covariance_pose_matrix->item(5, 3);
        ___qtablewidgetitem70->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem71 = tableWidget_covariance_pose_matrix->item(5, 4);
        ___qtablewidgetitem71->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem72 = tableWidget_covariance_pose_matrix->item(5, 5);
        ___qtablewidgetitem72->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        tableWidget_covariance_pose_matrix->setSortingEnabled(__sortingEnabled1);

        tabWidget_covariance_matrix->setTabText(tabWidget_covariance_matrix->indexOf(Pose), QCoreApplication::translate("GraphEdgeRTWidget", "Pose", nullptr));

        const bool __sortingEnabled2 = tableWidget_covariance_velocity_matrix->isSortingEnabled();
        tableWidget_covariance_velocity_matrix->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem73 = tableWidget_covariance_velocity_matrix->item(0, 0);
        ___qtablewidgetitem73->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem74 = tableWidget_covariance_velocity_matrix->item(0, 1);
        ___qtablewidgetitem74->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem75 = tableWidget_covariance_velocity_matrix->item(0, 2);
        ___qtablewidgetitem75->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem76 = tableWidget_covariance_velocity_matrix->item(0, 3);
        ___qtablewidgetitem76->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem77 = tableWidget_covariance_velocity_matrix->item(0, 4);
        ___qtablewidgetitem77->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem78 = tableWidget_covariance_velocity_matrix->item(0, 5);
        ___qtablewidgetitem78->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem79 = tableWidget_covariance_velocity_matrix->item(1, 0);
        ___qtablewidgetitem79->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem80 = tableWidget_covariance_velocity_matrix->item(1, 1);
        ___qtablewidgetitem80->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem81 = tableWidget_covariance_velocity_matrix->item(1, 2);
        ___qtablewidgetitem81->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem82 = tableWidget_covariance_velocity_matrix->item(1, 3);
        ___qtablewidgetitem82->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem83 = tableWidget_covariance_velocity_matrix->item(1, 4);
        ___qtablewidgetitem83->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem84 = tableWidget_covariance_velocity_matrix->item(1, 5);
        ___qtablewidgetitem84->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem85 = tableWidget_covariance_velocity_matrix->item(2, 0);
        ___qtablewidgetitem85->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem86 = tableWidget_covariance_velocity_matrix->item(2, 1);
        ___qtablewidgetitem86->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem87 = tableWidget_covariance_velocity_matrix->item(2, 2);
        ___qtablewidgetitem87->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem88 = tableWidget_covariance_velocity_matrix->item(2, 3);
        ___qtablewidgetitem88->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem89 = tableWidget_covariance_velocity_matrix->item(2, 4);
        ___qtablewidgetitem89->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem90 = tableWidget_covariance_velocity_matrix->item(2, 5);
        ___qtablewidgetitem90->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem91 = tableWidget_covariance_velocity_matrix->item(3, 0);
        ___qtablewidgetitem91->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem92 = tableWidget_covariance_velocity_matrix->item(3, 1);
        ___qtablewidgetitem92->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem93 = tableWidget_covariance_velocity_matrix->item(3, 2);
        ___qtablewidgetitem93->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem94 = tableWidget_covariance_velocity_matrix->item(3, 3);
        ___qtablewidgetitem94->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem95 = tableWidget_covariance_velocity_matrix->item(3, 4);
        ___qtablewidgetitem95->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem96 = tableWidget_covariance_velocity_matrix->item(3, 5);
        ___qtablewidgetitem96->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem97 = tableWidget_covariance_velocity_matrix->item(4, 0);
        ___qtablewidgetitem97->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem98 = tableWidget_covariance_velocity_matrix->item(4, 1);
        ___qtablewidgetitem98->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem99 = tableWidget_covariance_velocity_matrix->item(4, 2);
        ___qtablewidgetitem99->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem100 = tableWidget_covariance_velocity_matrix->item(4, 3);
        ___qtablewidgetitem100->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem101 = tableWidget_covariance_velocity_matrix->item(4, 4);
        ___qtablewidgetitem101->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem102 = tableWidget_covariance_velocity_matrix->item(4, 5);
        ___qtablewidgetitem102->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem103 = tableWidget_covariance_velocity_matrix->item(5, 0);
        ___qtablewidgetitem103->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem104 = tableWidget_covariance_velocity_matrix->item(5, 1);
        ___qtablewidgetitem104->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem105 = tableWidget_covariance_velocity_matrix->item(5, 2);
        ___qtablewidgetitem105->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem106 = tableWidget_covariance_velocity_matrix->item(5, 3);
        ___qtablewidgetitem106->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem107 = tableWidget_covariance_velocity_matrix->item(5, 4);
        ___qtablewidgetitem107->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem108 = tableWidget_covariance_velocity_matrix->item(5, 5);
        ___qtablewidgetitem108->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        tableWidget_covariance_velocity_matrix->setSortingEnabled(__sortingEnabled2);

        tabWidget_covariance_matrix->setTabText(tabWidget_covariance_matrix->indexOf(Velocity), QCoreApplication::translate("GraphEdgeRTWidget", "Velocity", nullptr));

        const bool __sortingEnabled3 = tableWidget_covariance_acceleration_matrix->isSortingEnabled();
        tableWidget_covariance_acceleration_matrix->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem109 = tableWidget_covariance_acceleration_matrix->item(0, 0);
        ___qtablewidgetitem109->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem110 = tableWidget_covariance_acceleration_matrix->item(0, 1);
        ___qtablewidgetitem110->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem111 = tableWidget_covariance_acceleration_matrix->item(0, 2);
        ___qtablewidgetitem111->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem112 = tableWidget_covariance_acceleration_matrix->item(0, 3);
        ___qtablewidgetitem112->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem113 = tableWidget_covariance_acceleration_matrix->item(0, 4);
        ___qtablewidgetitem113->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem114 = tableWidget_covariance_acceleration_matrix->item(0, 5);
        ___qtablewidgetitem114->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem115 = tableWidget_covariance_acceleration_matrix->item(1, 0);
        ___qtablewidgetitem115->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem116 = tableWidget_covariance_acceleration_matrix->item(1, 1);
        ___qtablewidgetitem116->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem117 = tableWidget_covariance_acceleration_matrix->item(1, 2);
        ___qtablewidgetitem117->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem118 = tableWidget_covariance_acceleration_matrix->item(1, 3);
        ___qtablewidgetitem118->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem119 = tableWidget_covariance_acceleration_matrix->item(1, 4);
        ___qtablewidgetitem119->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem120 = tableWidget_covariance_acceleration_matrix->item(1, 5);
        ___qtablewidgetitem120->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem121 = tableWidget_covariance_acceleration_matrix->item(2, 0);
        ___qtablewidgetitem121->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem122 = tableWidget_covariance_acceleration_matrix->item(2, 1);
        ___qtablewidgetitem122->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem123 = tableWidget_covariance_acceleration_matrix->item(2, 2);
        ___qtablewidgetitem123->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem124 = tableWidget_covariance_acceleration_matrix->item(2, 3);
        ___qtablewidgetitem124->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem125 = tableWidget_covariance_acceleration_matrix->item(2, 4);
        ___qtablewidgetitem125->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem126 = tableWidget_covariance_acceleration_matrix->item(2, 5);
        ___qtablewidgetitem126->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem127 = tableWidget_covariance_acceleration_matrix->item(3, 0);
        ___qtablewidgetitem127->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem128 = tableWidget_covariance_acceleration_matrix->item(3, 1);
        ___qtablewidgetitem128->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem129 = tableWidget_covariance_acceleration_matrix->item(3, 2);
        ___qtablewidgetitem129->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem130 = tableWidget_covariance_acceleration_matrix->item(3, 3);
        ___qtablewidgetitem130->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem131 = tableWidget_covariance_acceleration_matrix->item(3, 4);
        ___qtablewidgetitem131->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem132 = tableWidget_covariance_acceleration_matrix->item(3, 5);
        ___qtablewidgetitem132->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem133 = tableWidget_covariance_acceleration_matrix->item(4, 0);
        ___qtablewidgetitem133->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem134 = tableWidget_covariance_acceleration_matrix->item(4, 1);
        ___qtablewidgetitem134->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem135 = tableWidget_covariance_acceleration_matrix->item(4, 2);
        ___qtablewidgetitem135->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem136 = tableWidget_covariance_acceleration_matrix->item(4, 3);
        ___qtablewidgetitem136->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem137 = tableWidget_covariance_acceleration_matrix->item(4, 4);
        ___qtablewidgetitem137->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem138 = tableWidget_covariance_acceleration_matrix->item(4, 5);
        ___qtablewidgetitem138->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem139 = tableWidget_covariance_acceleration_matrix->item(5, 0);
        ___qtablewidgetitem139->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem140 = tableWidget_covariance_acceleration_matrix->item(5, 1);
        ___qtablewidgetitem140->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem141 = tableWidget_covariance_acceleration_matrix->item(5, 2);
        ___qtablewidgetitem141->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem142 = tableWidget_covariance_acceleration_matrix->item(5, 3);
        ___qtablewidgetitem142->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem143 = tableWidget_covariance_acceleration_matrix->item(5, 4);
        ___qtablewidgetitem143->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem144 = tableWidget_covariance_acceleration_matrix->item(5, 5);
        ___qtablewidgetitem144->setText(QCoreApplication::translate("GraphEdgeRTWidget", "0", nullptr));
        tableWidget_covariance_acceleration_matrix->setSortingEnabled(__sortingEnabled3);

        tabWidget_covariance_matrix->setTabText(tabWidget_covariance_matrix->indexOf(Acceleration), QCoreApplication::translate("GraphEdgeRTWidget", "Acceleration", nullptr));
    } // retranslateUi

};

namespace Ui {
    class GraphEdgeRTWidget: public Ui_GraphEdgeRTWidget {};
} // namespace Ui

QT_END_NAMESPACE

#endif // GRAPH_EDGE_RT_WIDGET_UI_H
